### ISSUE TITLE
Word is cut starting at accentuated character when editing a label in the diagrams

### ISSUE THREAD

**Issue by cbrun** [eclipse-syson/syson#211]
Hi,

steps to reproduce: 
- create a general view diagram
- create a Part Def
- use direct edit to rename it to something with a non ascii character, for instance "Café italien"
- the Part is named "Caf" whereas I would have expected it to be named "Café italien"

workaround: when using the property forms it works as expected.

**Comment by AxelRICHARD** [comment]
Fixed with #324
