### ISSUE TITLE
Remove edge creation action from Interconnection view diagram

### ISSUE THREAD

**Issue by jessymallet** [eclipse-syson/syson#224]
From Interconnection view diagram, user can create many edges between 2 parts : 
 * Become nested part, 
 * Dependency,
 * Redefinition,
 * Subsetting,
 * Allocation.

Only "Become nested part" and "Allocation" edge should be possible. Moreover when user create a "Dependency" for example, the dependency is not represented on the diagram. Its creation should be forbidden if we cannot represent it on the diagram.

### **Expected behavior** : 

User should not be able to create the following edges on Interconnection view diagram : 
 * Dependency,
 * Redefinition,
 * Subsetting,

### **Actual screenshot behavior** : 

![image](https://github.com/eclipse-syson/syson/assets/24290600/7d97e148-9dba-49c6-94cd-8cb18dd5d092)

**Comment by AxelRICHARD** [comment]
All edges tool have been removed from _Parts_ in _InterconnectionView_ diagrams, as it is not the diagram for such links.
If you want to move parts, you just have to D&D them.
