### ISSUE TITLE
Graphical Drag&Drop should Drag&Drop element and all its content

### ISSUE THREAD

**Issue by jessymallet** [eclipse-syson/syson#226]
When user launch a graphical Drag&Drop of a given element, we can see the change of semantic parent of the element (and so the whole cluster of its content)  but also the change of graphical parent of this element.
However, after Drag&Drop, content node of initial node disappear. Only the main node is represented.

### **Expected behavior:**
Drag&Drop of a given element should re-draw this element in the new parent and its content should always be represented 

### **Actual screenshot behavior:**
![graphicalDrag Drop](https://github.com/eclipse-syson/syson/assets/24290600/02f31d76-7583-4d11-a1bb-608ea5d6ff14)

**Comment by gdaniel** [comment]
This issue has been solved in #657.
Note that the size of the element changes after the drop (it is reset to the default size, modulo the size of its content). This is, I believe, a limitation of Sirius Web: we can't provide the size of the node as part of a `ViewCreationRequest`. 
![DropContainer](https://github.com/user-attachments/assets/ff926d1e-6ac9-4c75-a688-ef61225a2747)
