### ISSUE TITLE
Should interfaces be allowed in the namespace of a part?

### ISSUE THREAD

**Issue by RadowGit** [eclipse-syson/syson#261]
I'm not sure if _Interfaces_ should be allowed in the namespace of a _Part_. Aren't only the _Ports_ defined for a _Part_ and then _Interafces_ and connections separately? 
This confuses me a bit because _Interface_ should be connected to at least both _Parts_.

![image](https://github.com/eclipse-syson/syson/assets/163411637/580451a0-9ca9-42f9-a565-b5e9e3066ce5)

![image](https://github.com/eclipse-syson/syson/assets/163411637/b01bc05b-d2bc-4e73-9dad-f9e78bda2ede)

I understand the example in the specification a bit different: 

![image](https://github.com/eclipse-syson/syson/assets/163411637/e1c13814-1f9e-4e0c-bf1f-90acd9031001)

**Comment by AxelRICHARD** [comment]
Hello,

You are right, the `InterfaceUsage` created by the `New interface` edge tool in the Interconnection View diagram shouldn't be under its edge source.
It should be created under closest containing Definition/Package.

Regards,

**Comment by RadowGit** [comment]
@AxelRICHARD Hi, this issue still looks unsolved to me. I’m looking forward to dive deeper into the Syson modeling with newer (pre) releases, but I really need the interface display fixed at the right  structural level first. 
Unfortunately, my java dev skills aren’t quite up to tackling the code myself. Any updates or pointers would be appreciated

**Comment by AxelRICHARD** [comment]
Hello,
A fix has been provided and should be integrated in the codebase soon.
Please reopen if you need.
Regards,
