### ISSUE TITLE
Usage of "indirect" qualified name in direct edit typing is not properly handled

### ISSUE THREAD

**Issue by AxelRICHARD** [eclipse-syson/syson#292]
For example, you have an attribute name _actualSpeed_ and you want to type this attribute with the attribute def _SpeedUnit_ from the _ISQSpaceTime_ standard library.
You should be able to use the three syntaxes in the direct edit:
- SpeedUnit => OK
- ISQSpaceTime::SpeedUnit => OK
- SI::SpeedUnit => KO

_SI::SpeedUnit_ should also work because _SI_ imports _ISQ::*_ and _ISQ_ imports _ISQSpaceTime::*_

**Comment by gdaniel** [comment]
This was fixed in #666
