### ISSUE TITLE
Add existing elements (recursive) add nested elements as rectangular children nodes in addition to list children nodes

### ISSUE THREAD

**Issue by AxelRICHARD** [eclipse-syson/syson#293]
Here is the result of the execution of the _Add existing elements (recursive)_ tool in a general-view diagram, based on the model visible in the _Explorer_ view:
![Capture d’écran 2024-05-15 à 17 05 42](https://github.com/eclipse-syson/syson/assets/717752/5bfbcecf-f258-4009-8558-098e1d6e3c0c)

The _attribute_ element has been added as a nested rectangular node in addition to being added into the _attributes_ compartment.

It would be better if the _attribute_ element was not added as a nested rectangular node, only as a list item into the _attributes_ compartment.

**Comment by gdaniel** [comment]
I think this was fixed in #487
