### ISSUE TITLE
Improve the support for parallel states

### ISSUE THREAD

**Issue by gdaniel** [eclipse-syson/syson#307]
We can only have one type of state in the _state transition_ compartment: parallel or non-parallel. We remove the tools to create one when the compartment already contains an element of the other type.

This is not correct w.r.t. the specification: a state can contain parallel and non-parallel states. It is not clear if we should have different tools to create parallel and non-parallel states.

We do not support restrictions on transitions for parallel states:
8.3.17.5: if a state is parallel none of the `ownedActions` (which includes `ownedStates`) may have any incoming or outgoing `Transitions`

**Comment by arnauddieumegard** [comment]
I will work on this !

**Comment by arnauddieumegard** [comment]
This also requires to prevent modification of the parallel attribute which may lead to an incorrect model.
e.g. create a state, add two sub states, add a transition between the sub states and then set the parent state as parallel.
