### ISSUE TITLE
Interconnection Representation is not working correctly

### ISSUE THREAD

**Issue by Krusty84** [eclipse-syson/syson#340]
Hello Dear Team!

I have the following Sysml example:

package Test {
	package Definitions {
		part def Part1;
		part def Part2;
		part def Part22;
		
		port def Pa {
			in port1 : Part22;
		}
		interface def InterfaceDef {
			end port1:Pa;
			end port2:~Pa;
			flow of Part22 from port1.port1 to port2.port1; 
		}
		connection def ConnectionDef {
			end end1 : Part1;
			end end2 : Part2;
		}
	}
	package InterConnections {
		import Definitions::*;

		part 'part A' { 
			part part5 : Part1;
			part part6 : Part2;
			connection connectionName  connect part5 to part6;
		}
		part 'part B' { 
			part part1:Part1 {
				port p4:Pa;
			}
			part part2:Part2 {
				port p2: ~Pa;
			}
			interface interface1 : InterfaceDef connect part1.p4 to part2.p2;
		}
		part 'part C' { 
			part part3 : Part1;
			part part4 : Part2;
			connection connection1 : ConnectionDef connect part3 to part4;
		}
	}
}

In Eclipse via Plantuml plugin this Interconnection view looks right:

![image](https://github.com/eclipse-syson/syson/assets/44873126/0ffe7814-cd3d-49c2-b7e8-d56141122038)
![image](https://github.com/eclipse-syson/syson/assets/44873126/f92dded4-2534-4f6f-997f-603bd562b189)
![image](https://github.com/eclipse-syson/syson/assets/44873126/a4aa5e8f-8f8f-4744-9cda-534f310a9590)
![image](https://github.com/eclipse-syson/syson/assets/44873126/e8e8eeae-c06a-48a0-b090-1879b8ba81b3)
![image](https://github.com/eclipse-syson/syson/assets/44873126/acd63dda-e495-4052-86f0-3ef1f84e134c)
![image](https://github.com/eclipse-syson/syson/assets/44873126/2e1a0480-8943-45ca-bde6-0c3b6bd279ba)

But, in SysON this Interconnection view looks wrong (or may be I am wrong:)):

![image](https://github.com/eclipse-syson/syson/assets/44873126/da2dda1d-e7d8-48ca-9324-a0fc3c7cbd59)

![image](https://github.com/eclipse-syson/syson/assets/44873126/599525bc-daee-47be-acff-3a6b9046cb2e)

![image](https://github.com/eclipse-syson/syson/assets/44873126/6304cc3c-fc64-449b-a5cd-bdabe921ce6d)

[InterconnectionTest.sysml.txt](https://github.com/user-attachments/files/15514738/InterconnectionTest.sysml.txt)

Can you help me? Thank you/Merci!

**Comment by Krusty84** [comment]
Or is this my wrong? Or ?

**Comment by AxelRICHARD** [comment]
Hello,
I'm sorry but I don't have the time to analyze your example.
What I can say is some SysMLv2 concepts are not handled yet in the InterconnectionView diagram (e.g. _flow_) so that's why you may notice some differences between another tool and SysON.
We're working on it, so it should be better and better through the next releases.

**Comment by Krusty84** [comment]
Dear @AxelRICHARD thank you!
