### ISSUE TITLE
Running on Mac OS gives Whitelabel Error Page

### ISSUE THREAD

**Issue by matthias-priebe** [eclipse-syson/syson#375]
Hello,
I checked out the last Release Version v2024.5.0 of SysON from Git and compiled it succesfully following the tutorial. When I now try to run it using "docker compose up" on my Macbook with MacOS and access it through the browser I get the following screen:

`Whitelabel Error Page
This application has no explicit mapping for /error, so you are seeing this as a fallback.

Fri Jun 07 05:26:51 UTC 2024
There was an unexpected error (type=Not Found, status=404).`

I cannot see any issues in the console.

**Comment by AxelRICHARD** [comment]
Hello,
Could you follow https://github.com/eclipse-syson/syson/discussions/83#discussioncomment-8663531 and tell me if you succeed in running SysON please?

**Comment by matthias-priebe** [comment]
That works perfectly! Thank you! Maybe it would be cool to Link the post, somewhere in the Documentation?

**Comment by AxelRICHARD** [comment]
Yes, we will provide an official documentation soon, and it will be part of it.
