### ISSUE TITLE
Denpendency edge element should follow its source element when it is moved

### ISSUE THREAD

**Issue by jerome-obeo** [eclipse-syson/syson#399]
When the source of a dependency edge is moved inside another container element, the element associated with the edge should also be moved.

### Actual behavior

![edge_does_not_follow_dnd](https://github.com/eclipse-syson/syson/assets/128463513/fdf58cc7-74b4-40c7-8292-6c9dbe0a1c87)

### Expected behavior

The `dependency` element should be automatically moved inside `Package1`.

**Comment by AxelRICHARD** [comment]
After discussion, `dependency` should stay as it is, even if its `source` is moved somewhere else.
