### ISSUE TITLE
Add SysML-v2 API support

### ISSUE THREAD

**Issue by wucke13** [eclipse-syson/syson#573]
The [documentation's FAQ](https://doc.mbse-syson.org/syson/main/user-manual/faq/faq.html) already states the following:

> We’re fully compatible with the SysML v2 standard. Models can be shared using the SysML v2 textual notation and the SysML v2 API.

However, the [integration documentation](https://doc.mbse-syson.org/syson/main/user-manual/integration/api.html) than discloses:

> The SysML v2 API is unavailable. For interoperability with SysON, use the provided file exchange format.

I see the API as the primary value proposition as SysML-v2, and thus I'd be happy to see API support in syson. I did not see an issue nor a milestone for that in this project, hence I filed this issue.

**Comment by AxelRICHARD** [comment]
Hello,
Sorry for this inconsistency.
This has been fixed.
Regards,
