### ISSUE TITLE
Cannot display owned or unowned memberships using direct notation

### ISSUE THREAD

**Issue by sandmallard** [eclipse-syson/syson#611]
Packages can be displayed using nested notation but cannot be shown on a General View with the direct notation for owned and unowned memberships. The memberships do not appear in the diagram palette -- it appears that only the allocation relationship is available at this time.

**Comment by AxelRICHARD** [comment]
Hello,
Can you be more precise with a textual and graphical example please? 
I don't understand what is the point you try to demonstrate here.
I also don't understand what you called "nested notation" and "direct notation".
Regards,

**Comment by sandmallard** [comment]
Of course. Apologies that I did not include more specific details. Referencing subclause 8.2.3.5 and table 33 of the v2 specification in this issue. The graphical notation for the SysML V2 general view allows for displaying owned members and imported (unowned) members of a namespace by nesting one within another (nested notation) or alternatively to display the membership or import relationship between the elements (direct notation). 
Here is a reference to the direct notation for the membership and import relationships from the specification (subclause 8.2.3.5, page 192)
![image](https://github.com/user-attachments/assets/8fab5178-8ad0-4a61-a515-33e8ce503000)
And an example of what it would look like:
![image](https://github.com/user-attachments/assets/26d18f8b-6d21-4184-9598-9869e15baaf1)

Here is an example of the nested notation from the specification (Annex A, page 613)
![image](https://github.com/user-attachments/assets/c2fd62e5-0368-4f14-a10d-f390bde35058)

**Comment by AxelRICHARD** [comment]
Thank you for the details, I understand now.
Indeed, we currently only provide the "nested" notation for Packages in SysON.
The alternative "direct" notation would also be great but we didn't plan to add it in the tool in the next release.
It does not mean it will never be implemented, our priorities are evaluated again after each release.
Regards,

**Comment by sandmallard** [comment]
It makes sense that the nested notation is the priority as it is more intuitive. My role is providing training to end users, so I am providing feedback as I work through the current features and apologize if I am ahead of the release schedule. I appreciate the prompt responses here and look forward to seeing SysOn gain popularity.
