### ISSUE TITLE
Cannot display standard library elements in General View

### ISSUE THREAD

**Issue by sandmallard** [eclipse-syson/syson#612]
I have imported various SysML library elements such as ShapeItems from the General Domain Library using the textual syntax. The import shows up in the model browser and I can select the filter option to display the SysML library elements; however, I am unable to view any standard library elements upon dragging them to the diagram pane.

**Comment by AxelRICHARD** [comment]
Hello,
There is no need to import standard libraries into a SysON project.
There are already there automatically.

Just create a project with the "SysMLv2" template from the homepage, uncheck the filter "Hide SysML Standard Libraries" and you will see the "ShapeItems" library appears in the Explorer view.
<img width="609" alt="Capture d’écran 2024-07-30 à 09 09 09" src="https://github.com/user-attachments/assets/959a157c-0e82-4f1f-832e-d86edf482e64">

Then you can create a "General View" diagram from the root package of this library, and then import some elements through the dedicated action, or by d&d elements from the Explorer view.

<img width="1346" alt="Capture d’écran 2024-07-30 à 09 11 54" src="https://github.com/user-attachments/assets/941888af-4838-42e5-ad54-14196ce2c55f">

Regards,

**Comment by sandmallard** [comment]
I'm not sure what I was doing yesterday, but apparently, I was not using the tool correctly. I thought I'd followed the approach you indicated and was not seeing the library element upon dragging and dropping it onto the General View. This morning, I was successful. Thank you for the clear direction.
