### ISSUE TITLE
Ports inheritance appears to be wrong

### ISSUE THREAD

**Issue by RadowGit** [eclipse-syson/syson#643]
I have created ports and interface usages inside the interconnection view. Only one port of a nested part is connected to the outside / is shared with the parent part. Adding existing elements in the general view, the ^ports appear to be wrong.

![AA_1](https://github.com/user-attachments/assets/a736af0f-f8f0-481d-af62-d2367fefbc32)
![AA_2](https://github.com/user-attachments/assets/16ce0603-d526-4364-912a-f89920ebee26)

**Comment by gdaniel** [comment]
Hi,

Thanks for the report. We have to look at how we handle inherited members for composite usage. This is in our roadmap, we'll get back to you once we have investigated the issue.

Regards
