### ISSUE TITLE
Missing commons-io library in syson-application-configuration

### ISSUE THREAD

**Issue by YashzAlphaGeek** [eclipse-syson/syson#71]
Hello Team,

While building the application I came across the problem because of the missing dependency in syson-application-configuration.

<img width="1143" alt="2024-02-06_21h31_52" src="https://github.com/eclipse-syson/syson/assets/18661896/9af8dc6f-e393-4b36-b6ee-10bf2db84c5f">

I do know the solution that we need to add the dependency in the pom.xml.

<dependency>
    <groupId>commons-io</groupId>
    <artifactId>commons-io</artifactId>
    <version>2.15.1</version>
</dependency>

Thank you in advance.

**Comment by YashzAlphaGeek** [comment]
I have configured the settings.xml in my $HOME/.m2/settings.xml with github-sirius-emfjson & github-sirius-web. I am using teh maven version - 3.6.3.

**Comment by AxelRICHARD** [comment]
Ok, It's strange, but I will add the dependency explicitly if it can help you.

**Comment by YashzAlphaGeek** [comment]
Thank you @AxelRICHARD
