### ISSUE TITLE
Drag'n drop too sensible when clicking on packages

### ISSUE THREAD

**Issue by dvojtise** [eclipse-syson/syson#791]
when dealing with package structure, currently, the only way is to use the graphical view to show/manage the nesting of package (no move action from the Explorer ?)

unfortunately, it seems that the click is often misinterpreted as a drag'n drop and thus moves element out of it container.

Sometime placing the element behind the original package and hidding the element.

this is quite annoying as it make the edition imprecise, especially since there is no Ctrl+Z to undo this unexpected action

https://github.com/user-attachments/assets/832010c5-5beb-44e1-9e6f-5f580952fa06

https://github.com/user-attachments/assets/4ab1a317-ca17-42ed-87ca-8dc95a02e357

tested with SysON v2024.9.1 (started via docker compose up)

**Comment by AxelRICHARD** [comment]
Hello,

Thank you for the feedback, we appreciate it!

As you may already know SysON relies on Sirius Web for this part, so there is nothing we can do directly in SysON.
We will talk about that with the Sirius Web team, see if there's something we can do.

D&D inside Explorer view & undo with Ctrl+Z will come in Sirius Web soon so I hope it will solve your problems.

Regards,

**Comment by dvojtise** [comment]
is there any issue opened on Sirius Web concerning this point ?
(as the Ctrl+z and Explorer features are only recovery workaround for the initial problem of weird model move)

**Comment by AxelRICHARD** [comment]
No there is no ticket opened in Sirius Web for the sensitivity of the D&D yet.
