### ISSUE TITLE
License confusion

### ISSUE THREAD

**Issue by Rots** [eclipse-syson/syson#822]
> then contents of LICENSE-LGPL are GPL not LGPL 

 _Originally posted by @Rots in [0464756](https://github.com/eclipse-syson/syson/commit/046475680e8913db373ba7ff67edee589acefc8a#r148588017)_

**Comment by gdaniel** [comment]
Hi @Rots, thanks for your interest in SysON!
I have created a pull request to fix the issue you reported.
