### ISSUE TITLE
Node.js missing from Installation Requirements 

### ISSUE THREAD

**Issue by joshreve** [eclipse-syson/syson#853]
Installation requirements list is missing the need for Node.js in order to get .sysml import working.  Non-docker installations will need to install Node.js and add it to the path for the syside to run and allow sysml format imports and element creation.

From the error log stating issues running node, I determined the missing requirement.  Upon installation, the locally installed server operated as intended, matching the docker version functionality.

Installation guide page below should include a mention of Node.js for syside / sysml format support.
https://github.com/eclipse-syson/syson/edit/main/doc/content/modules/installation-guide/pages/requirements.adoc

**Comment by AxelRICHARD** [comment]
Hello, thank you for your interest in SysON.
You're right, I will update the documentation soon to fix that.
Thank you,
Regards,
